export const Category_Constant = {
  "Hành Động": "hanh-dong",
  "Phiêu Lưu": "phieu-luu",
  "Hoạt Hình": "hoat-hinh",
  "Phim Hài": "phim-hai",
  "Hình Sự": "hinh-su",
  "Tài Liệu": "tai-lieu",
  "Chính Kịch": "chinh-kich",
  "Gia Đình": "gia-dinh",
  "Giả Tưởng": "gia-tuong",
  "Lịch Sử": "lich-su",
  "Kinh Dị": "kinh-di",
  "Phim Nhạc": "phim-nhac",
  "Bí Ẩn": "bi-an",
  "Lãng Mạn": "lang-man",
  "Khoa Học Viễn Tưởng": "khoa-hoc-vien-tuong",
  "Gây Cấn": "gay-can",
  "Chiến Tranh": "chien-tranh",
  "Miền Tây": "mien-tay",
};
